### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by wyc** [sajari/fuzzy#6]
```
$ go build
# github.com/sajari/fuzzy
../../../github.com/sajari/fuzzy/fuzzy.go:128: undefined: UseAutocomplete
```

Did you try compiling this before merging the latest PR?

**Comment by mish15** [comment]
Hmm strange, yeah I wrote tests. Apologies, having a look now to see what
happened.

**Comment by wyc** [comment]
Thanks for the speedy response!

**Comment by mish15** [comment]
no worries, sorry for the stupidity, no idea how that happened, like it
missed my last save...

On 3 March 2015 at 09:17, wyc <notifications@github.com> wrote:

> Thanks for the speedy response!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sajari/fuzzy/issues/6#issuecomment-76838744>.
>



-- 
*Hamish Ogilvy*
Sajari Pty Ltd
*t:  +61 (*0) 414 658 353  |  *e: *hogilvy@sajari.com
*w:*  www.sajari.com
